_core:
  default_config_hash: QDFjOXYIYVwCPQYHY4wAx4DUqOEkNaZokIx6DGApR9I
langcode: pt-br
enable_globally: 0
enable_globally_on_admin_routes: false
default_challenge: captcha/Math
description: ''
title: ''
administration_mode: false
administration_mode_on_admin_routes: false
whitelist_ips: ''
wrong_captcha_response_message: 'A sua resposta para o CAPTCHA não foi correta.'
default_validation: 1
persistence: 1
enable_stats: true
log_wrong_responses: true
