_core:
  default_config_hash: HENvUIeX6xNPGRB1w3z6rT9a71LM_hKXATF6XrM9WvM
langcode: pt-br
smtp_on: false
smtp_host: mail.aktivo.com.br
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_autotls: true
smtp_timeout: 30
smtp_username: plataforma.associado@aktivo.com.br
smtp_password: Firjan@2023
smtp_from: plataforma.associado@aktivo.com.br
smtp_fromname: No-reply
smtp_client_hostname: mail.aktivo.com.br
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: gserrao@firjan.com.br
smtp_reroute_address: ''
smtp_debugging: true
prev_mail_system: php_mail
smtp_keepalive: false
