settings:
  default_submit_button_label: Enviar
  default_reset_button_label: Reiniciar
  default_delete_button_label: Eliminar
  default_preview_next_button_label: Pré-visualizar
  default_preview_label: Pré-visualizar
  dialog_options:
    narrow:
      title: Estreito
    wide:
      title: Largo
element:
  default_more_title: Mais
